### ISSUE TITLE
Output to file

### ISSUE THREAD

**Issue by Twiebie** [spatie/http-status-check#17]
Currently it outputs a summary in the console, but because the actual links are printed while the scan runs it's quite messy having to scroll back up and find the broken links.

A nice feature would be to pass an option to allow printing to a file with for example the links not returning a 2xx response.

**Comment by freekmurze** [comment]
Totally agree that the tool should have an option to write the non 2xx responses to a file. I'd accept a pull request for this.

**Comment by ramirovjr** [comment]
As I started to implement the feature, some questions appeared, like:

- If the file exists, will it be overwritten?
- Will it be necessary to check for permissions to write the file?
- Should we use an abstraction (i.e.: Flysystem) to manipulate the file?

**Comment by freekmurze** [comment]
Thank you for putting time into this.

- since we're running at the console, we can just ask the user if the file should be overwritten
- nah, just let it fail if there's no permission to write to the file
- seems like overkill, let's just use `file_put_contents`.

**Comment by ramirovjr** [comment]
Ok, tonight I'll make the PR.

**Comment by ramirovjr** [comment]
@freekmurze forgot to change old array styles to new ones in the test, late at night =). I can fix it tomorrow.

**Comment by ramirovjr** [comment]
Fixed the issues reported by StyleCI and squashed the commits.
If there's anything missing, please, report. Thanks!

I'm pretty sure that the implementation could be improved and I'm open to suggestions, but this one was the simplest one from my point of view.

**Comment by freekmurze** [comment]
Implemented in `v2.1.0` 🎉

**Comment by Twiebie** [comment]
Open a ticket for an idea and come back a couple days later to see somebody implemented it - open source is a beautiful thing.

Thanks a lot @ramirovjr!

**Comment by ramirovjr** [comment]
@Twiebie no problem, I'm glad I could help and also thanks @freekmurze for the opportunity to contribute to the project.
