### ISSUE TITLE
Error on --output option

### ISSUE THREAD

**Issue by encodia** [spatie/http-status-check#29]
Hi there,

using this command:

`http-status-check scan http://www.mywebsite.com --output=mywebsite.log.txt`

I am getting:

> [Symfony\Component\Console\Exception\RuntimeException]
> The "--output" option does not exist.

Any ideas? Am I missing anything?

Thank you

**Comment by freekmurze** [comment]
Which version our you running?

You can upgrade to the latest version using `composer global update`.

**Comment by encodia** [comment]
Hi @freekmurze,

I did install your product this morning. I think I'd get the latest one.

**Comment by freekmurze** [comment]
Run `composer global show` to know for sure. `http-status-code` should be on `2.2.0`

**Comment by encodia** [comment]
I think you're right @freekmurze 

```
spatie/crawler            1.3.1  Crawl all internal links found on a website
spatie/http-status-check  1.0.2  CLI tool to crawl a website and check HTTP status code
```

May u suggest to me what I need to do?

My best

**Comment by freekmurze** [comment]
The newest versions of our packages require PHP7
