### ISSUE TITLE
Build PHAR

### ISSUE THREAD

**Issue by simondubois** [spatie/http-status-check#3]
Hi,

First, thanks for this good & useful package.
I used it in different applications and it helped to find broken pages.

I am now moving to docker and would like to include it in my image.
Is it possible to distribute this package as a PHAR file so it is easier to deploy ?

Thanks,

**Comment by freekmurze** [comment]
I'm glad you find the package useful 😄

I've got no experience with PHAR files, so this is something you have to find out on your own.
