### ISSUE TITLE
Tel: links are crawled

### ISSUE THREAD

**Issue by Rias500** [spatie/http-status-check#42]
When you have a link to a phone number: `<a href="tel:0123456789">Call me</a>` the crawler tries to pick up on it and returns a 404.

It doesn't do this for `mailto` so I guess an exception should be added.

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this.

**Comment by filipac** [comment]
@Rias500 are you sure the crawler picks up the tel link? I don't get the url in the output.

> Start scanning http://localhost:8080
> 
> [2018-01-23 14:53:51] 200 OK - http://localhost:8080/
> [2018-01-23 14:53:51] 200 OK - http://localhost:8080/link1
> [2018-01-23 14:53:51] 200 OK - http://localhost:8080/link2
> [2018-01-23 14:53:51] 302 Found - http://localhost:8080/link4
> [2018-01-23 14:53:51] 200 OK - http://localhost:8080/link3
> [2018-01-23 14:53:52] 200 OK - http://example.com/
> [2018-01-23 14:53:52] 404 Not Found - http://localhost:8080/notExists (found on http://localhost:8080/link3)
> 
> Crawling summary
> ----------------
> Crawled 5 url(s) with statuscode 200
> Crawled 1 url(s) with statuscode 302
> Crawled 1 url(s) with statuscode 404

**Comment by filipac** [comment]
This should be fixed in https://github.com/spatie/crawler/pull/12/files

**Comment by filipac** [comment]
@freekmurze you can close this :)
