### ISSUE TITLE
Version 3.0 returns 301 on website to check

### ISSUE THREAD

**Issue by TomasVotruba** [spatie/http-status-check#43]
This command works well with 2.5, but with 3.0 not anymore:

```bash
> vendor/bin/http-status-check scan https://tomasvotruba.cz --output invalid-links.txt

Start scanning https://tomasvotruba.cz

[2018-02-19 10:34:26] 301 Moved Permanently - https://tomasvotruba.cz/
```

Might be related to Cloudflare I'm using.

**Comment by freekmurze** [comment]
Probably related to cloudflare indeed. It seems to redirect to the `www` version of your site on `http`.

![screen shot 2018-02-19 at 12 28 06](https://user-images.githubusercontent.com/483853/36375652-62cf4082-1570-11e8-9ba2-9f6ddba64b62.png)

**Comment by TomasVotruba** [comment]
It worked with 2.5.
