### ISSUE TITLE
Not working on L5.6

### ISSUE THREAD

**Issue by rvizcaino80** [spatie/http-status-check#45]
When trying to install via composer I get:

Problem 1
    - Installation request for spatie/http-status-check ^3.0 -> satisfiable by spatie/http-status-check[3.0.0].
    - Conclusion: remove symfony/console v3.3.12
    - Conclusion: don't install symfony/console v3.3.12
    - spatie/http-status-check 3.0.0 requires symfony/console ^4.0 -> satisfiable by symfony/console[v4.0.0, v4.0.1, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8].
    - Can only install one of: symfony/console[v4.0.0, v3.3.12].
    - Can only install one of: symfony/console[v4.0.1, v3.3.12].
    - Can only install one of: symfony/console[v4.0.2, v3.3.12].
    - Can only install one of: symfony/console[v4.0.3, v3.3.12].
    - Can only install one of: symfony/console[v4.0.4, v3.3.12].
    - Can only install one of: symfony/console[v4.0.5, v3.3.12].
    - Can only install one of: symfony/console[v4.0.6, v3.3.12].
    - Can only install one of: symfony/console[v4.0.7, v3.3.12].
    - Can only install one of: symfony/console[v4.0.8, v3.3.12].
    - Installation request for symfony/console (locked at v3.3.12) -> satisfiable by symfony/console[v3.3.12].

**Comment by freekmurze** [comment]
You need Symfony 4 in order to use the package.
