### ISSUE TITLE
BasicHTTP authentication support

### ISSUE THREAD

**Issue by josefglatz** [spatie/http-status-check#54]
Hi,

would it be possible to add options to enable crawling a website which is only available through http basic auth?

Or as a workaround: how do I have to structure my cmdline call to add authentiction headers?

**Comment by freekmurze** [comment]
This is currently not supported. The easiest way to let our crawler crawl a hidden site would to start a a specific url  (eg.`https://mysite.com?secret=mysecretvalue`). You should modify your app so it display any pages to a visitor that used that url. Of course this isn't terribly secure.
