### ISSUE TITLE
Not every option is included 

### ISSUE THREAD

**Issue by SimoniusVonZyrene** [spatie/http-status-check#55]
The "--output" option does not exist.

**Comment by freekmurze** [comment]
It does: https://github.com/spatie/http-status-check/blob/894e0c269c7bce6f8f48f55538b61c1ee1401ff9/src/ScanCommand.php#L34-L39

**Comment by SimoniusVonZyrene** [comment]
what do you see when typing following command? 

http-status-check scan https://example.com --output=log.txt

**Comment by SimoniusVonZyrene** [comment]
<img width="866" alt="1__d438980_chp-12099_____zsh_" src="https://user-images.githubusercontent.com/3594379/44849551-c233aa00-ac5a-11e8-8853-c22cb2e3aef5.png">

**Comment by freekmurze** [comment]
Are you sure you are using v3?
