### ISSUE TITLE
Feature Request: Full output log in parsable format

### ISSUE THREAD

**Issue by bobemoe** [spatie/http-status-check#60]
I'm wanting to use the *full* crawl output to use in other apps.

Currently I can redirect stdout to a file and then open that in the other apps, but parsing the format requires a bit of regexp, and due to spaces in response reasons and not quoting it may be troublesome to perfect. I'm thinking CSV format output may be better.

I'm half way through implementing:

- Add a new flag `-f --csv <filename>` that outputs the entire crawl as a csv file.

But then thought that maybe:

- Modify the `-o --output` format to be CSV, and add another flag `-f --full` to specify for all responses not just errors to be outputted. 

Would you be interested in this? Shall I make a PR so you can see what I've done, or just link to my repo?

**Comment by bobemoe** [comment]
This works well so far: https://github.com/bobemoe/http-status-check/commit/5e28ac14f7b0e2aee67c294b1139e891ae1da6b1

**Comment by freekmurze** [comment]
Feel free to PR this, if the code is simple enough I'll merge it. 

Make sure your PR contains tests and an updated readme.

Thanks!

**Comment by bobemoe** [comment]
OK, I'm playing with the testing server now.. I see my previous PR broke some.. I will submit another PR to fix that soon. sorry :/

Also I can add more tests to help debug #62 if you like?
