### ISSUE TITLE
Invalid status code in Response.php

### ISSUE THREAD

**Issue by clarkeash** [spatie/http-status-check#68]
I was running `scan` against a site and got the following error:

```
In Response.php line 151:

  Status code must be an integer value between 1xx and 5xx.
```

Presumably, something has used a non-standard status code, but I don't know the URL as it doesn't come out in the error, also do you know where `Response.php` is as its not part of this package from what I can see.

**Comment by bobemoe** [comment]
The issue is with guzzle, I found this patch fixed it: https://github.com/guzzle/guzzle/pull/2591.patch

If you want to follow the issue: https://github.com/guzzle/guzzle/issues/2534 or https://github.com/spatie/crawler/issues/271


https://github.com/spatie/crawler/issues/271
