### ISSUE TITLE
how it work in ubuntu

### ISSUE THREAD

**Issue by vahidalvandi** [spatie/http-status-check#70]
hey i install it with bash

**$ sudo composer require spatie/http-status-check**

also in bash

**$ http-status-check scan https://example.com**

**http-status-check: command not found**

**Comment by devNajjary** [comment]
I have the same problem.

**Comment by devNajjary** [comment]
i solve this problem.
 you can run direct way.

`> php ~/.config/composer/vendor/bin/http-status-check scan https://google.com
`
or

`> php ~/.composer/vendor/bin/http-status-check scan https://google.com
`
