### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by freekmurze** [spatie/http-status-check#77]
One of the tests is failing on GitHub Actions. This should be fixed.

**Comment by Bapawe** [comment]
Since both fixes https://github.com/spatie/http-status-check/pull/78 and https://github.com/spatie/crawler/pull/343 are merged, this issue should be fixed when the new patch version is being released of spatie/crawler v4 and composer.json is updated to use this new release.

**Comment by freekmurze** [comment]
Thanks!
