### ISSUE TITLE
PHP8 version doesnt work

### ISSUE THREAD

**Issue by m-bosch** [spatie/http-status-check#80]
When installing  http-status-check the following error occured:
```Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - spatie/crawler[4.7.0, ..., 4.7.5] require php ^7.1 -> your php version (8.0.2) does not satisfy that requirement.
```

I was working on a PR to update the composer to the crawler 6.* version but in version 5 there were breaking changes that are not explained in an update guide.

So when i changed the version to 6, all the tests break because `Spatie\Crawler\CrawlAllUrls` has been removed. I think there are several deeper issues now, and i dont think i can solve them the way you want. It is also more a thing like: "in what way you want it to work"

**Comment by freekmurze** [comment]
Feel free to PR the improvements that you need 👍
